build:
  stage: build
  image:
    name: ghcr.io/sdc0/manjaro-qt6-ffmpeg
    entrypoint: ["/bin/sh", "-c"]
  script:
    - mkdir build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=Debug ..
    - cmake --build . -j4
  artifacts:
    paths:
      - build/AVQt/libAVQt_static.a
      - build/AVQt/libAVQt.so
      - AVQt/
    expire_in: 1 week