default:
  image:
    name: sdc0/manjaro-qt-ffmpeg:qt5
    entrypoint: ["/bin/sh", "-c"]
  tags:
    - amd64

build:
  stage: build
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
    - mkdir build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=Debug -DQT_VERSION=5 ..
    - cmake --build . -j2
