build:
  stage: build
  image: manjarolinux/base
  script:
    - mkdir build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=Debug ..
    - cmake --build . -j4
  artifacts:
    paths:
      - build/AVQt/libAVQt.so
      - AVQt/
    expire_in: 1 week
