build:
  stage: build
  image:
    name: wiktorguz/qt6
    entrypoint: ["/bin/bash", "-c"]
  script:
    - mkdir build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=Debug ..
    - cmake --build . -j4
  artifacts:
    paths:
      - build/AVQt/libAVQt.so
      - AVQt/
    expire_in: 1 week
