default:
  tags:
    - amd64

build-qt5:
  stage: build
  image:
    name: sdc0/manjaro-qt-ffmpeg:qt5
    entrypoint: [ "/bin/sh", "-c" ]
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
    - mkdir build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=Debug -DQT_VERSION=5 ..
    - cmake --build . -j2

build-qt6:
  stage: build
  image:
    name: sdc0/manjaro-qt-ffmpeg:qt6
    entrypoint: [ "/bin/sh", "-c" ]
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
    - mkdir build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=Debug -DQT_VERSION=6 ..
    - cmake --build . -j2
