cache:
  paths:
    - apt-cache/

build:
  stage: build
  image: wiktorguz/qt6
  before_script:
    - apt update && apt upgrade -o dir::cache::archives="apt-cache" -y
    - apt install -o dir::cache::archives="apt-cache" -y software-properties-common
    - add-apt-repository -y ppa:ubuntu-toolchain-r/test && apt update
    - apt install -o dir::cache::archives="apt-cache" -y libswscale-dev libswresample-dev libpostproc-dev libavutil-dev libavresample-dev libavformat-dev libavfilter-extra libavfilter-dev libavdevice-dev libavcodec-extra libavcodec-dev ffmpeg git cmake libvulkan-dev gcc-10 gcc-10-base gcc-10-doc g++-10 libopenal-dev
  script:
    - mkdir build && cd build
    - cmake -DCMAKE_C_COMPILER=/usr/bin/gcc-10 -DCMAKE_CXX_COMPILER=/usr/bin/g++-10 -DCMAKE_BUILD_TYPE=Debug .. && cmake --build . -j4
  artifacts:
    paths:
      - build/AVQt/libAVQt.so
      - AVQt/
    expire_in: 1 week
