default:
  image:
    name: sdc0/manjaro-qt-ffmpeg:qt5
    entrypoint: ["/bin/sh", "-c"]

build:
  stage: build
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
    - mkdir build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=Debug -DQT_VERSION=5 ..
    - cmake --build . -j$(nproc)
    - cd ..
    - mkdir build-release
    - cd build-release
    - cmake -DCMAKE_BUILD_TYPE=Release -DQT_VERSION=5 ..
    - cmake --build . -j$(nproc)
