default:
  image:
    name: sdc0/manjaro-qt6-ffmpeg
    entrypoint: ["/bin/sh", "-c"]
  tags:
    - arm64

build:
  stage: build
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
    - mkdir build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=Debug ..
    - cmake --build . -j$(nproc)
    - cd ..
    - mkdir build-release
    - cd build-release
    - cmake -DCMAKE_BUILD_TYPE=Release ..
    - cmake --build . -j$(nproc)
  artifacts:
    paths:
      - build/AVQt/libAVQt_static.a
      - build/AVQt/libAVQt.so
      - AVQt/
    expire_in: 1 week
